before:
    hooks:
        - go mod tidy
        - go generate ./...
        - make test
builds:
    - env:
        - CGO_ENABLED=0
      ldflags:
        - -s -w -X github.com/caioeverest/vulcan/infra/config.Version={{ .Version }}
      goos:
        - linux
        - darwin
archives:
    - name_template: '{{ .ProjectName }}_{{ .Version }}-{{ .Os }}-{{ .Arch }}'
      replacements:
        '386': i386
        darwin: macOS
        linux: Linux
        amd64: x86_64
      files:
        - LICENSE
checksum:
    name_template: checksums.txt
snapshot:
    name_template: '{{ .Tag }}-next'
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
