before:
    hooks:
        - go mod tidy
        - go generate ./...
        - make test
builds:
    - env:
        - CGO_ENABLED=0
      ldflags:
        - -s -w -X github.com/caioeverest/vulcan/infra/config.Version={{ .Version }}
      goos:
        - linux
        - darwin
checksum:
    name_template: checksums.txt
snapshot:
    name_template: '{{ .Tag }}-next'
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'

archives:
    - name_template: '{{ .ProjectName }}_{{ .Version }}-{{ .Os }}-{{ .Arch }}'
      replacements:
        '386': i386
        darwin: macOS
        linux: Linux
        amd64: x86_64
      files:
        - LICENSE

snapcrafts:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    summary: Scanfold tool to create projects based on templates.
    description: This app is a CLI tool that helps you to create projects from predefined templates.
    grade: stable
    confinement: classic
    publish: true

brews:
  - tap:
      owner: caioeverest
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/caioeverest/vulcan
    description: Scanfold tool to create projects based on templates.
    license: GPL-3.0
    test: |
      system "#{bin}/vulcan -v"
    dependencies:
    - name: go
    install: |-
      bin.install "vulcan"
