// Code generated by mockery v2.5.1. DO NOT EDIT.

package project

import mock "github.com/stretchr/testify/mock"

// MockOption is an autogenerated mock type for the Option type
type MockOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: p
func (_m *MockOption) Execute(p *Project) {
	_m.Called(p)
}
